# Generated by Django 4.1.3 on 2023-07-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_cart_product_cart_product_qty_cart_to_user_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='city',
        ),
        migrations.RemoveField(
            model_name='page',
            name='education',
        ),
        migrations.RemoveField(
            model_name='page',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='page',
            name='state',
        ),
        migrations.AddField(
            model_name='intrest_followers',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
