# Generated by Django 4.1.3 on 2023-07-20 04:54

from django.db import migrations, models
import network.validators


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_remove_post_content_image_post_content_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_images',
        ),
        migrations.AddField(
            model_name='post',
            name='content_image',
            field=models.FileField(blank=True, null=True, upload_to='posts/', validators=[network.validators.file_size]),
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
