# Generated by Django 4.1.3 on 2023-07-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_friend_request_to_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='to_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_noti', to='network.page'),
        ),
    ]
