# Generated by Django 4.1.3 on 2023-07-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_notifications_to_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrest',
            name='intrest_category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
