# Generated by Django 4.1.3 on 2023-07-31 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_intrest_intrest_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='intrest_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrest_category', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='intrest',
            name='intrest_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.intrest_category'),
        ),
    ]
