# Generated by Django 4.1.3 on 2023-07-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_rename_intrest_category_intr_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_categories', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='intr_category',
        ),
    ]
